[package]
name = "web_browser"
version = "0.1.0"
authors = ["gann <garedaiki@outlook.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.7.0"
gdk = "0.11.0"
ureq = "0.11.2"