[package]
name = "web_browser"
version = "0.1.0"
authors = ["gann <daiki_17n1100521@nnn.ed.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.7.0"